% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Sep-2021 16:59:21
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------

p   = ('/Users/elinemertens/Downloads');
fn  = '2018_10_17_0018.abf';
fp  = fullfile(p,fn);
ss  = load('/Users/elinemertens/Data/Morphys-master/Matlab/Abfanalysis/Setupsettings_INF.mat');
ss  = ss.obj;
abf = Abffile(fp,ss);

%%

for i=1:numel(fn)
    data=abfload_pro(fn{i});
    if contains(fn{i}, 'H1')
        plotcolor='r';
    elseif contains(fn{i}, 'M1')
        plotcolor='g';
    end
    signal=normalize(mean(squeeze(data(:,1,:))'), 'range');
    stim=normalize(mean(squeeze(data(:,2,:))'), 'range');

    Fs = 10000;           % Sampling frequency
    L = length(signal);      % Signal length
    f = (0:L-1)*Fs/L;
    signal_fft=fft(signal);
    stim_fft=fft(stim);

    %plot
    %smoothed
    plot(f, smooth(abs(signal_fft)./abs(stim_fft)),plotcolor);
    xlim([0.5 35])
    hold on
%     %raw
%     plot(f, abs(signal_fft)./abs(stim_fft));
%     xlim([0.5 35])
end